### ISSUE TITLE
How is the data about other methods in D2Net Table 1 obtained?

### ISSUE THREAD

**Issue by henryccl** [CityU-AIM-Group/D2Net#1]
Hi, thank you for open sourcing D2Net, and I have to say that it is indeed a very good work!!!
I have a few doubts about what is reported in the paper.
In Table 1 it can be found that compared to previous methods D2Net achieved an almost overwhelming advantage, the authors trained and validated on BraTS2018 data after 3-fold cross-validation, where the compared methods include [Latent Correlation Representation Learning for Brain Tumor Segmentation With Missing MRI Modalities, Acn: Adversarial co-training network for brain tumor segmentation with missing modalities, ...] , but no specific implementation code is given in these papers. I compared the data provided in D2Net Table 1 with the data provided in the above papers and found that the results are not the same. How is the data about other methods in D2Net Table 1 obtained?

![( HLK7GLR8%MQ(_FNEN D`7](https://user-images.githubusercontent.com/44051761/173480413-26a0df74-8c41-4d4c-b667-15a8d1e887f1.png)

I would appreciate it if you could answer this question.

**Comment by QiushiYang** [comment]
Hi, apologies for the late reply. Thanks for you questions!
As you mentioned, some of comparisons did not release source codes, therefore, we reimplemented the strategies according to those papers based on our baseline. We re-trained them on our data splits and reported the results for a fair comparison.

**Comment by henryccl** [comment]
> Thank you for your answer.

**Comment by henryccl** [comment]
Thank you for your answer
