### ISSUE TITLE
The results

### ISSUE THREAD

**Issue by qiuchengjian** [CityU-AIM-Group/D2Net#5]
I would like to know how the results of the cited papers are calculated. It seems that they are not directly quoted, which is inconsistent with the results provided by the cited papers. As shown in Table 1, the results of ACNet are much less than the original paper. Looking forward to your answer, thank you very much

**Comment by QiushiYang** [comment]
The results of other methods are re-trained on our dataset and experimental settings by ourselves, maintaining the same setting as D2Net for a fair comaprison. Towards the ACNet, note that we re-trained it and evaluated it on the missing modality setting consisting of 16 cases. We guess that the inferiority of ACNet may contribute to the reason that the orignial ACNet was designed only for one specific case of missing modality, and it does not work well on other multiple cases.
