### ISSUE TITLE
Fig 6 and 7 plotting 

### ISSUE THREAD

**Issue by aldiak** [CityU-AIM-Group/D2Net#6]
Greetings Sir, I went through your paper and would like to know if your features visualization code for figures 6 and 7 if available. Thank you

**Comment by QiushiYang** [comment]
Thanks for your interests. The Fig. 6 & 7 are directly plotted via tsne tool using the features from the network. You can also try to plot them during the training phase.

**Comment by aldiak** [comment]
Okay, thank you 🙏
